name: Release Please

on:
  push:
    branches:
      - develop

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[
              {"type":"build","section":"Build","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"ci","section":"CI/CD","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"refactor","section":"Refactor","hidden":false},
              {"type":"revert","section":"Reverts","hidden":false},
              {"type":"style","section":"Style","hidden":false},
              {"type":"test","section":"Tests","hidden":false}
            ]'
