name: Type Check

on:  
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  Type-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up node 
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: 'Create .env file'
        run: echo "${{ secrets.DOT_ENV_FILE }}" > .env

      - run: yarn
        name: Install dependencies

      - run: yarn type-check
        name: Type Check
