name: Run Unit Tests
run-name: ✅ Running unit tests
on:  
  push:
  pull_request:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
        name: Install dependencies
      - run: yarn test
        name: Run unit tests
